### ISSUE TITLE
Missing trailing null byte for `BCrypt#generate` call

### ISSUE THREAD

**Issue by Marcono1234** [exploit-org/NetArmor#1]
The code here seems to call Bouncy Castle's `BCrypt#generate` with a byte array without trailing null byte:
https://github.com/exploit-org/NetArmor/blob/d3c6915e19c749d9f89a0248e491fe06e16283a2/src/main/java/org/exploit/armor/password/BCryptPasswordEncoder.java#L35

This means two passwords where one is the repetition of the other, e.g. "abc" and "abcabc", will have the same hash. See https://github.com/bcgit/bc-java/issues/393.

Note: Because I am not familiar with this project setup, I am reporting this only based on the source code of this project, but I hope this report is useful nonetheless.

**Comment by xlloit** [comment]
Hey! Yes, you are right, thank you for the valuable observation. It was missed mechanically.
But this repository is not maintained, since the project has been transferred under the auspices of OWASP: [OWASP Netryx](https://github.com/OWASP/www-project-netryx)

I'll definitely be more attentive, when will prepare Netryx Password module. Thanks!
